Args:
	model: stacked_NN
	optimizer: SGD
	optimizer_args: {}
	hyperoptimizer: RMSProp
	hyperoptimizer_args: {}
	num_hyperoptimizers: 4
	loss_fn: CrossEntropyLoss
	dataset: MNIST
	alpha: 1e-06
	kappa: None
	num_epochs: 10
	batch_size: 1024
	baseline: False
	device: cuda
	Alpha Values: {0: 1e-06, 1: 5e-09, 2: 3.333333333333333e-09, 3: 2.5e-09, 4: 1.9999999999999997e-09}
	Using 4 GPUs

***Beginning Training***
	Epoch[1/10]: Training Loss = 2.29101
	Epoch[2/10]: Training Loss = 2.29099
	Epoch[3/10]: Training Loss = 2.29097
	Epoch[4/10]: Training Loss = 2.29095
	Epoch[5/10]: Training Loss = 2.29093
	Epoch[6/10]: Training Loss = 2.29090
	Epoch[7/10]: Training Loss = 2.29087
	Epoch[8/10]: Training Loss = 2.29084
	Epoch[9/10]: Training Loss = 2.29080
	Epoch[10/10]: Training Loss = 2.29076
***Training Complete***

Final Optimizer Parameters
	alpha : 3.999191449111095e-06
	mu : 0.0

***Testing Results***
==============================
Test Accuracy = 9.750 %
Test Error = 90.250 %
==============================

Plotted Lists:
Epochs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
alpha: [9.999999974752427e-07, 1.3255062185635325e-06, 1.6207968656090088e-06, 1.9168351172993425e-06, 2.2124440874904394e-06, 2.5093991098401602e-06, 2.8071822271158453e-06, 3.1035967822390376e-06, 3.4028835216304287e-06, 3.7006607271905523e-06, 3.999191449111095e-06]
mu: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Loss: [0.0022528281807899474, 2.291005954106649, 2.2909915795644125, 2.2909739327748615, 2.29095306892395, 2.2909289394378662, 2.29090158551534, 2.2908709573109944, 2.2908371116638184, 2.29079998626709, 2.2907595657348634]
Traceback (most recent call last):
  File "/scratch/bes1g19/DeepLearning/CW/taskdef.py", line 192, in <module>
    experiments.plot(args.alpha, args.kappa, args.optimizer, args.optimizer_args, args.hyperoptimizer, args.hyperoptimizer_args, args.model, f"{args.alpha}/{args.num_hyperoptimizers}")
  File "/mainfs/scratch/bes1g19/DeepLearning/CW/packages/utils/train_val.py", line 287, in plot
    plt.savefig(f'../plots/{src}/{path}.png')
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 977, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 541, in print_png
    mpl.image.imsave(
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../plots/stacked_NN/1e-06/4.png'
