Args:
	model: stacked_NN
	optimizer: SGD
	optimizer_args: {}
	hyperoptimizer: RMSProp
	hyperoptimizer_args: {}
	num_hyperoptimizers: 2
	loss_fn: CrossEntropyLoss
	dataset: MNIST
	alpha: 1e-06
	kappa: None
	num_epochs: 10
	batch_size: 1024
	baseline: False
	device: cuda
	Alpha Values: {0: 1e-06, 1: 5e-09, 2: 3.333333333333333e-09}
	Using 4 GPUs

***Beginning Training***
	Epoch[1/10]: Training Loss = 2.31253
	Epoch[2/10]: Training Loss = 2.31252
	Epoch[3/10]: Training Loss = 2.31250
	Epoch[4/10]: Training Loss = 2.31247
	Epoch[5/10]: Training Loss = 2.31245
	Epoch[6/10]: Training Loss = 2.31242
	Epoch[7/10]: Training Loss = 2.31238
	Epoch[8/10]: Training Loss = 2.31234
	Epoch[9/10]: Training Loss = 2.31230
	Epoch[10/10]: Training Loss = 2.31225
***Training Complete***

Final Optimizer Parameters
	alpha : 4.00183625970385e-06
	mu : 0.0

***Testing Results***
==============================
Test Accuracy = 12.670 %
Test Error = 87.330 %
==============================

Plotted Lists:
Epochs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
alpha: [9.999999974752427e-07, 1.325188691225776e-06, 1.621279920982488e-06, 1.9169228835380636e-06, 2.213776724602212e-06, 2.510256763343932e-06, 2.8092065349483164e-06, 3.10634504785412e-06, 3.4035481348837493e-06, 3.7026409245299874e-06, 4.00183625970385e-06]
mu: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Loss: [0.002273999857902527, 2.3125334720611574, 2.3125171456654865, 2.312497222137451, 2.3124735551198325, 2.3124462679545084, 2.3124153146107993, 2.3123805596669516, 2.312342314147949, 2.312300248972575, 2.312254531987508]
Traceback (most recent call last):
  File "/scratch/bes1g19/DeepLearning/CW/taskdef.py", line 192, in <module>
    experiments.plot(args.alpha, args.kappa, args.optimizer, args.optimizer_args, args.hyperoptimizer, args.hyperoptimizer_args, args.model, f"{args.alpha}/{args.num_hyperoptimizers}")
  File "/mainfs/scratch/bes1g19/DeepLearning/CW/packages/utils/train_val.py", line 287, in plot
    plt.savefig(f'../plots/{src}/{path}.png')
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/pyplot.py", line 977, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/backends/backend_agg.py", line 541, in print_png
    mpl.image.imsave(
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/matplotlib/image.py", line 1675, in imsave
    image.save(fname, **pil_kwargs)
  File "/lyceum/bes1g19/.conda/envs/py3venv/lib/python3.10/site-packages/PIL/Image.py", line 2317, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../plots/stacked_NN/1e-06/2.png'
